# Generated by Django 3.0.8 on 2020-07-25 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('S', '판매'), ('B', '구매')], max_length=10)),
                ('status', models.CharField(choices=[('W', '양도 대기'), ('C', '양도 완료'), ('P', '양도 진행중')], max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
                ('reserve_price', models.IntegerField()),
                ('food_price', models.IntegerField()),
                ('people', models.IntegerField()),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='content.Post')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
